#!/bin/bash

#sed -i '/pbr_init/d' /etc/rc.local
#sed -i '/exit 0/i sudo bash /usr/share/oc-pbr/pbr_init &' /etc/rc.local
sudo chown -R root:vyattacfg /config/auth/
sudo chown -R root:vyattacfg /config/scripts/
sudo update-rc.d oc-vyos defaults
sudo mkdir -p /var/log/oc
touch /var/log/oc/oc-vyos.log
echo "" > /var/log/oc/vyos_monitor
sudo chown vyos:users -R /var/log/oc /usr/share/vyos /usr/share/oc-pbr
cp /usr/share/oc-pbr/dhclient-script /sbin/dhclient-script
sudo cp /usr/share/vyos/oc_config_server/vyos-log /etc/logrotate.d/vyos-log
