#!/bin/bash
echo "dhclient: $reason"
case $reason in
    BOUND|RENEW|REBIND|REBOOT)
      if [ "eth0" == $interface ]; then
          sudo bash /usr/share/oc-pbr/pbr_init &
          echo "Management pbr is set"
      fi
      ;;
esac

