#!/bin/bash

# start docker and load the configurator image
docker daemon --raw-logs &
docker load -i /usr/share/SCUI/docker/images/configurator-docker
docker load -i /usr/share/SCUI/docker/images/visibility-docker
docker load -i /usr/share/SCUI/docker/images/elastic
docker load -i /usr/share/SCUI/docker/images/graphite
