#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

echo "dhclient: $reason"
case $reason in
    BOUND|RENEW|REBIND|REBOOT)
      if [ "eth0" == $interface ]; then
          sudo bash /usr/share/vyos-pbr/pbr_init &
          echo "Management pbr is set"
      fi
      ;;
esac

