#!/bin/bash
case $reason in
    BOUND|RENEW|REBIND|REBOOT)
      if [ "eth0" == $interface ]; then
          echo $new_routers > /usr/share/vyos-pbr/eth0_route
      else
          unset new_routers
      fi
      echo "Default gateway has been cleared"
      ;;
esac
