#!/bin/bash
set -eu

# create SCUI directory
sudo mkdir -p ${TMP_MOUNT_PATH}/usr/share/SCUI
# create 'images' directory to hold docker images
sudo mkdir -p ${TMP_MOUNT_PATH}/usr/share/SCUI/docker/images
# copy the directory 'docker' to VM
sudo cp -rL ${VISIBILITY_GIT_PATH}/visibility ${TMP_MOUNT_PATH}/usr/share/

#copy docker images to VM
sudo cp -L ${DOCKER_IMAGES_PATH}/visibility-docker ${TMP_MOUNT_PATH}/usr/share/SCUI/docker/images/
sudo cp -L ${DOCKER_IMAGES_PATH}/configurator-docker ${TMP_MOUNT_PATH}/usr/share/SCUI/docker/images/
sudo wget ${DOCKER_IMAGES_URL}/elastic -O ${TMP_MOUNT_PATH}/usr/share/SCUI/docker/images/elastic
sudo wget ${DOCKER_IMAGES_URL}/graphite -O ${TMP_MOUNT_PATH}/usr/share/SCUI/docker/images/graphite

