#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

sudo chown -R root:vyattacfg /config/auth/
sudo chown -R root:vyattacfg /config/scripts/
sudo update-rc.d vyos defaults
sudo mkdir -p /var/log/vyos
touch /var/log/vyos/vyos.log
echo "" > /var/log/vyos/vyos_monitor
sudo chown vyos:users -R /var/log/vyos /usr/share/vyos /usr/share/vyos-pbr
cp /usr/share/vyos-pbr/dhclient-script /sbin/dhclient-script
sudo cp /usr/share/vyos/config_server/vyos-log /etc/logrotate.d/vyos-log
